name: roshambo
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  animated_text_kit: ^3.0.0
  rflutter_alert: ^1.1.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.7+14
  firebase_storage: ^5.2.0
  permission_handler: ^5.0.1+1
  liquid_progress_indicator: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: Russo One
      fonts:
        - asset: assets/RussoOne-Regular.ttf

